{
	"version": 1739447876,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"images/bg-sheet0.png",
		"images/dragonleft-sheet0.png",
		"images/jonsnow-sheet0.png",
		"images/fireleft.png",
		"images/dragonright-sheet0.png",
		"images/fireright.png",
		"images/coin-sheet0.png",
		"images/ground-sheet0.png",
		"images/sprite11sheet-sheet0.png",
		"images/tiledbackground.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/coin collect (1).m4a",
		"media/coin collect (1).ogg",
		"media/fire.m4a",
		"media/fire.ogg",
		"media/bg (1).m4a",
		"media/bg (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}